apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-install
  namespace: monitoring
data:
  install.sh: |
    helm repo add grafana https://grafana.github.io/helm-charts
    helm repo update
    helm install loki grafana/loki-stack -n monitoring