name: CI Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

env:
  BACKEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-backend
  FRONTEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-frontend

jobs:

  # =========================
  # Backend Test
  # =========================
  backend-test:
    name: Backend Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.26"
          cache: true

      - name: Run Go Tests
        working-directory: ./backend
        run: |
          go mod tidy
          go test ./...

  # =========================
  # Secret Scan
  # =========================
  gitleaks:
    name: Gitleaks Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # =========================
  # Backend Build
  # =========================
  backend-build:
    name: Backend Image Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: false
          load: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save Backend Image
        run: |
          docker save ${{ env.BACKEND_IMAGE }}:${{ github.sha }} -o backend.tar

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-image
          path: backend.tar

  # =========================
  # Frontend Build
  # =========================
  frontend-build:
    name: Frontend Image Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: false
          load: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save Frontend Image
        run: |
          docker save ${{ env.FRONTEND_IMAGE }}:${{ github.sha }} -o frontend.tar

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-image
          path: frontend.tar

  # =========================
  # Trivy Scan
  # =========================
  trivy-scan:
    name: Trivy Images Security Scan
    runs-on: ubuntu-latest

    needs:
      - backend-build
      - frontend-build

    steps:
      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-image

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-image

      - name: Load Backend Image
        run: docker load -i backend.tar

      - name: Load Frontend Image
        run: docker load -i frontend.tar

      - name: Trivy Backend Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      - name: Trivy Frontend Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

  # =========================
  # Push Docker Images
  # =========================
  docker-push:
    name: Push Docker Images
    runs-on: ubuntu-latest

    needs:
      - trivy-scan

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend-image

      - uses: actions/download-artifact@v4
        with:
          name: frontend-image

      - name: Load Backend Image
        run: docker load -i backend.tar

      - name: Load Frontend Image
        run: docker load -i frontend.tar

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Backend Image
        run: |
          docker push ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          docker tag ${{ env.BACKEND_IMAGE }}:${{ github.sha }} ${{ env.BACKEND_IMAGE }}:latest
          docker push ${{ env.BACKEND_IMAGE }}:latest

      - name: Push Frontend Image
        run: |
          docker push ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          docker tag ${{ env.FRONTEND_IMAGE }}:${{ github.sha }} ${{ env.FRONTEND_IMAGE }}:latest
          docker push ${{ env.FRONTEND_IMAGE }}:latest

  # =========================
  # Summary
  # =========================
  summary:
    name: CI Pipeline Job Done..
    runs-on: ubuntu-latest

    needs:
      - backend-test
      - gitleaks
      - backend-build
      - frontend-build
      - trivy-scan
      - docker-push

    steps:
      - name: Summary
        run: |
          echo "CI Pipeline Completed Successfully"
          echo "Docker images created"
          echo "Docker cache enabled"
          echo "Images scanned before push"
          echo "Parallel jobs enabled"
